# Generated by Django 5.0.6 on 2024-05-26 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PravnoLice',
            fields=[
                ('lozinka', models.CharField(max_length=20)),
                ('pib', models.IntegerField(db_column='PIB', unique=True)),
                ('mail', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('odobren', models.BooleanField(default=False)),
                ('idk', models.OneToOneField(db_column='idK', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='aplikacija.korisnik')),
            ],
            options={
                'db_table': 'PRAVNO_LICE',
                'managed': True,
            },
        ),
    ]
