# Generated by Django 5.0.6 on 2024-05-26 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0002_alter_administracija_options_alter_adresa_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administracija',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='adresa',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='artikal',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='fizickolice',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='idesa',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='komentar',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='korisnik',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='kupon',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='narudzbina',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='narudzbinaartikal',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='popustartikal',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='popustgrupa',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='popustpib',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pravnolice',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='recenzija',
            options={'managed': False},
        ),
    ]
