# Generated by Django 5.0.6 on 2024-05-26 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0003_alter_administracija_options_alter_adresa_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pravnolice',
            options={'managed': True},
        ),
    ]
