# Generated by Django 5.0.6 on 2024-05-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0004_alter_pravnolice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pravnolice',
            name='mail',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pravnolice',
            name='odobren',
            field=models.BooleanField(default=False),
        ),
    ]
