# Generated by Django 5.0.6 on 2024-05-27 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0002_pravnolice'),
        ('aplikacija', '0005_pravnolice_mail_pravnolice_odobren'),
    ]

    operations = [
    ]
