# Generated by Django 5.0.6 on 2024-07-31 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacija', '0006_merge_20240527_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'OCENA',
                'managed': False,
            },
        ),
    ]
